### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by AustinLMayes** [comment]
You seem to like to steal maps and other Avicus assets/branding.

Enjoy your ban from our organization.

**Comment by ghost** [comment]
>           You seem to like to steal maps and other Avicus assets/branding.
> Enjoy your ban from our organization.

Nothing is "Stealing" since everything is free to use lmfao.
also nice to see how you tried to put down our website on a illegal way
enjoy the firewall

**Comment by ghost** [comment]
https://gyazo.com/1881e9d6c857111f93cd79ad8b28b51e

**Comment by smitdalt** [comment]
Liscence for plugin code != liscence for branding and maps.

**Comment by Prodigy4532** [comment]
We are trying to re-create a nice network as AVN was, just that, we are not stealing nothing or trying to be best of you, i don't know why you are so angry, just that.

**Comment by jamesxsc** [comment]
If you are using the maps or branding (logos/name) you cannot do that. IIRC, that was made very clear upon the code release.

**Comment by ghost** [comment]
we are using the logos that was released inside website?
also we didnt even had the name "avicus" anywere

**Comment by ghost** [comment]
if you dont want people using it then remove the whole code or dont even make it public

**Comment by ghost** [comment]
and as far as i can see we are allowed to use it commercial (https://gyazo.com/995fb2e583f9a0b38bdcb8849e84bc4d)

**Comment by AustinLMayes** [comment]
@Thrasilias Quite sad to see you are evading a GitHub ban. As others have stated above, plugin/website code which was released in the repositories is free to use, hence the MIT license. Other works, such as maps and branding (this includes any logos and the Avicus Network name), are **NOT** free for use and any use of such violates US law. If you have any further questions, please feel free to contact us at support@avicus.net, instead of needlessly spamming issues here. 

@Prodigy4532 You stole over 100 pages of maps created specifically for the network without any form of license. I'm not angry, I just expected more from a previous map developer on the network who's responsibility it was to protect users' creations. If you need maps, I suggest using resource pile.

Both of your account have been banned from the organization. Continued evasion will result in more severe action.

**Pull request closed without merging**
